version: '2'
services:
  client-connection-prod:
    container_name: client-connection-prod
    build:
      context: .
      dockerfile: Dockerfile
    image: client-connection-prod
    ports:
      - 25000:25000
    networks:
      - trade_project

networks:
  trade_project:
    external: true