//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 04:35:26 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/orderValidation/clientorders", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.client.connection.ClientOrders;
